SET(BARTOLFLUXSYSTEMATICSEVALUATOR_LIB_LIST "-libSystematics")

SET(BARTOLFLUXSYSTEMATICSEVALUATOR_FEATURES_LIST)

SET(ROOT_INCLUDE_DIRS_SEP ${ROOT_INCLUDE_DIRS})
string(REPLACE ";" " -I" ROOT_INCLUDE_DIRS_SEP "-I${ROOT_INCLUDE_DIRS_SEP}")
SET(ROOT_DEFINITIONS_SEP ${ROOT_DEFINITIONS})
string(REPLACE ";" " " ROOT_DEFINITIONS_SEP "${ROOT_DEFINITIONS_SEP}")
SET(ROOT_LIBRARIES_SEP ${ROOT_LIBRARIES})
string(REPLACE ";" " -l" ROOT_LIBRARIES_SEP "-l${ROOT_LIBRARIES_SEP}")

# Set the creation date
string(TIMESTAMP CREATION_DATE "%d-%m-%Y")

string(REPLACE ";" " " BARTOLFLUXSYSTEMATICSEVALUATOR_FEATURES "${BARTOLFLUXSYSTEMATICSEVALUATOR_FEATURES_LIST}")
configure_file(${CMAKE_CURRENT_LIST_DIR}/../Templates/bartolfluxsystematicsevaluator-config.in
  "${PROJECT_BINARY_DIR}/bartolfluxsystematicsevaluator-config" @ONLY)
install(PROGRAMS
  "${PROJECT_BINARY_DIR}/bartolfluxsystematicsevaluator-config" DESTINATION
  bin)
